AWSTemplateFormatVersion: '2010-09-09'
Description: Video Preview System Infrastructure

Resources:
  FFmpegLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: ffmpeg-layer
      Description: Layer containing FFmpeg binaries
      CompatibleRuntimes:
        - python3.9
        - nodejs18.x
      LayerVersionArn: arn:aws:lambda:us-east-2:466206553767:layer:ffmpeg:1

